server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: order
    password: orderpass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  topics:
    ordersEvents: orders.events
    paymentsCommands: payments.commands
    paymentsEvents: payments.events
    inventoryCommands: inventory.commands
    inventoryEvents: inventory.events
  consumer:
    idempotency:
      enabled: true
